"""Add completed_at column to transactions table

Revision ID: 45d8aff96cfe
Revises: 914bc1066648
Create Date: 2025-05-30 14:41:47.941379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d8aff96cfe'
down_revision = '914bc1066648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cooldowns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.alter_column('total_games',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_players',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_volume',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('house_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('new_users',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('active_users',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('game_rooms', schema=None) as batch_op:
        batch_op.alter_column('room_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('bet_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('min_players',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_players',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_winner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('referrer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('referred_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('bonus_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_constraint('fk_transactions_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('wins',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('losses',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('losses',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wins',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_user_id_users', type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.alter_column('bonus_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('referred_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('referrer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_winner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('max_players',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_players',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('game_rooms', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('bet_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('room_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.alter_column('active_users',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('new_users',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('house_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('total_volume',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('total_players',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_games',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cooldowns', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
